### ISSUE TITLE
Nothing is showing in the textbox

### ISSUE THREAD

**Issue by Lavalinater9000** [EIA485/oscChatBoxMusic#1]
When i open the .exe, it shows connecting to OSC, but it never says connected. Is there a pre-required step i need to do for this to work?

**Comment by EIA485** [comment]
there is no connected msg in the code, try playing something and see if it says `updated osc to: songname`

if it shows some media playing but its not in green you can press enter to select that as the media source

**Comment by Lavalinater9000** [comment]
so to select it, i press enter and use the mouse to select?
![image](https://user-images.githubusercontent.com/56793412/193353681-8647f978-bf97-4031-9ea0-ad5bf173fe43.png)
because so far, when i pause and unpause it shows this message but i dont see any menu when i press enter

**Comment by EIA485** [comment]
press enter then use arrow keys to select then enter to confirm

**Comment by EIA485** [comment]
ive discovered a bug in the program where if the first audio source is not playing you cant open the select menu, il fix this bug. the work around for now is to play your first source then press enter in the window.

**Comment by EIA485** [comment]
fixed in [2.1](https://github.com/EIA485/oscChatBoxMusic/releases/tag/2.1.0.0)
